server:
  port: 8762
spring:  application:
    name: eureka-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/
management:  endpoints:    web:      exposure:        include:        - "*"
      cors:        allowed-origins:        - "*"
        allowed-methods:        - "*"