server:
  port: 8769  #eureka默认端口号
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
    preferIpAddress: true
  client:
    registerWithEureka: false 
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/