server:
  port: 8761  #eureka默认端口号
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
    preferIpAddress: true
  client:
    registerWithEureka: false 
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8769/eureka/